name: supplysync
description: "A Flutter project of SupplySync."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Main dependencies
  go_router: ^14.4.1 # Navigation
  flutter_bloc: ^9.0.0 # State management
  get_it: ^8.0.3 # Dependency injection
  flutter_secure_storage: ^9.2.2 # Secure storage
  shared_preferences: ^2.3.3 # Shared preferences
  fpdart: ^1.1.1 # Functional programming

  # External communication dependencies
  http: ^1.1.2 # HTTP requests
  permission_handler: ^11.3.1 # Permission handler
  local_auth: ^2.3.0 # Biometric authentication

  # Video, Camera, and Image dependencies
  mobile_scanner: ^6.0.2 # New QR_Code reader

  # UI dependencies
  cupertino_icons: ^1.0.8 # Cupertino icons
  responsive_builder: ^0.7.1 # Help make the app responsive
  flutter_native_splash: ^2.4.2 # To create splash screen

  # Debug dependencies
  logger: ^2.1.0 # Logger

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  # Create app icons
  # Configurations in [flutter_launcher_icons.yaml]
  flutter_launcher_icons: ^0.14.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
